Extended functionality of working with stubs
tinkoff-mobile-tech/TinkoffMockStrapping pull request #6
Opened 2022-08-04 11:26 UTC by DTuganova

1. Added headers parameter to HttpRequestProtocol to make it available to check headers parameters during tests
2. Added checking request body and stub body conformance for requests with same URLs and query parameters

2022-08-04 11:43 UTC, RomanGL requested changes
Требуются доработки

2022-08-04 11:43 UTC, RomanGL commented on Development/Source/Core/NetworkStubRequest.swift
> +    public let headersDictionary: [String : String]?
Предлагаю сделать словарь пустым, а не nil.

2022-08-04 11:43 UTC, RomanGL commented on Development/Source/Core/NetworkStubRequest.swift
> +        let isBodyMatched: Bool = {
Раньше не было проверки на соответствие bodyJson?
Также не увидел где проверяется соответствие headers.

2022-08-04 11:43 UTC, RomanGL commented on Development/Source/Core/NetworkStubRequest.swift
> +                  let requestBodyDictionary = convertToDictionary(jsonString: requestBodyString) else {
Зачем конвертировать JSON в словарь, чтобы потом снова ключи и значения в JSON превращать? Может быть есть другие способы сравнить JSON-ки?

2022-08-04 11:51 UTC, DTuganova commented on Development/Source/Core/NetworkStubRequest.swift
> +        let isBodyMatched: Bool = {
не было
соответствие headers пока не стала делать, так как, мне кажется, маловероятно, что будут запросы, в которых будут одинаковые URL, query и body.

2022-08-04 11:56 UTC, DTuganova commented on Development/Source/Core/NetworkStubRequest.swift
> +                  let requestBodyDictionary = convertToDictionary(jsonString: requestBodyString) else {
из bodyJson, к сожалению, получается достать только rawString, в и случае, а сравнивать две строки будет неправильно, так как параметры могут идти в строке в разном порядке и тогда стаб окажется неподходящим. А чтобы достать оттуда имя определенного параметра для проверки, нужно сначала конвертировать в словарь.

2022-08-05 10:24 UTC, DTuganova commented on Development/Source/Core/NetworkStubRequest.swift
> +        let isBodyMatched: Bool = {
добавила проверку на соотвествие headers

2022-08-05 11:48 UTC, RomanGL requested changes
Требуется доработка

2022-08-05 11:48 UTC, RomanGL commented on Development/Source/Core/BaseNetworkMocker.swift
> +            .sorted { $0.request.bodyJson?.rawString()?.count ?? 0 >
В этой проверке нет смысла. С другими параметрами мы просто берем более точно описывающий стаб, тогда как с длинной текста body связи не прослеживается.

2022-08-05 11:51 UTC, DTuganova commented on Development/Source/Core/BaseNetworkMocker.swift
> +            .sorted { $0.request.bodyJson?.rawString()?.count ?? 0 >
в этом случае тоже можно взять более точно описывающий стаб. сейчас существующая там проверка допускает, что в стабе будут только некоторые параметры указаны из запроса, соответственно, чем больше параметров body указано в стабе, тем точнее он описывает

2022-08-05 11:53 UTC, DTuganova commented on Development/Source/Core/BaseNetworkMocker.swift
> +            .sorted { $0.request.bodyJson?.rawString()?.count ?? 0 >
а нет, длина строки не указывает на количество параметров, действительно проверка бессмысленная

2022-08-05 15:13 UTC, merged